spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
    url: ${url}
    username: ${username}
    password: ${password}
  batch:
    job:
      enabled: false
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          time_zone: UTC
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        format_sql: true
    hibernate:
      ddl-auto: update
  jmx:
    enabled: false
logging:
  file:
    path: ./log
  level:
    liquibase: ERROR
    io.dsub: INFO
    org:
      reflections: ERROR
      springframework: ERROR
      hibernate: ERROR
    com.zaxxer.hikari: ERROR
server:
  shutdown: graceful