spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      auto-commit: false
    url: ${url}
    username: ${username}
    password: ${password}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          time_zone: UTC
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        bootstrap-mode: default
  jmx:
    enabled: false

logging:
  file:
    path: ./log
  level:
    io.dsub: INFO
    org:
      reflections: ERROR
      springframework:
        batch:
          core:
            listener: ERROR
            step:
              builder: ERROR
              item: ERROR
      hibernate: ERROR
    com.zaxxer.hikari: ERROR
server:
  shutdown: graceful