spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
    url: ${url}
    username: ${username}
    password: ${password}
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  jpa:
    properties:
      hibernate:
        jdbc:
          batch_size: 500
          time_zone: UTC
          batch_versioned_data: true
        order_updates: true
        order_inserts: true
        format_sql: true
    hibernate:
      ddl-auto: update
  data:
    jpa:
      repositories:
        # this is mandate as of initialization of JPA repositories
        # may live under the process EVEN AFTER the batch job is finished.
        # this is also can be a potential reason of spring batch not being exited
        # immediately after the job is done.
        bootstrap-mode: default
  jmx:
    enabled: false
  sql:
    init:
      mode: always
      schema-locations: db/{database}/schema.sql
logging:
  file:
    path: ./log
  level:
    io.dsub: INFO
    org:
      reflections: ERROR
      springframework:
        batch:
          core:
            listener: ERROR
            step:
              builder: ERROR
              item: ERROR
      hibernate: ERROR
    com.zaxxer.hikari: ERROR
server:
  shutdown: graceful