package io.dsub.discogs.batch.query;

import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;
import javax.persistence.JoinColumn;
import javax.persistence.Table;

public abstract class SqlJpaEntityQueryBuilder<T> implements JpaEntityQueryBuilder<T> {

  public static final String DEFAULT_SQL_INSERT_QUERY_FORMAT = "INSERT INTO %s(%s) SELECT %s";

  public static final String WHERE_CLAUSE_QUERY_FORMAT = "WHERE %s = %s";

  public static final String WHERE_CLAUSE_QUERY_INNER_SELECT_FORMAT =
      "(SELECT 1 FROM %s WHERE %s = %s)";

  @Override
  public String getInsertQuery(Class<? extends T> targetClass) {
    boolean idInclusive = !isIdAutoGenerated(targetClass);
    Map<String, String> mappings = getMappings(targetClass, idInclusive);
    String tblName = getTableName(targetClass);
    Field createdAt = getCreatedAtField(targetClass);
    Field lastModified = getLastModifiedField(targetClass);
    List<String> columns = new ArrayList<>(mappings.keySet());
    List<String> values = new ArrayList<>(mappings.values());
    String mappedValues = getFormattedValueFields(createdAt, lastModified, values);

    return String.format(
        DEFAULT_SQL_INSERT_QUERY_FORMAT, tblName, String.join(",", columns), mappedValues);
  }

  protected String getFormattedValueFields(
      Field createdAt, Field lastModifiedAt, List<String> values) {
    String[] parts = new String[values.size()];
    for (int i = 0; i < values.size(); i++) {
      String origin = values.get(i);
      if (createdAt != null && createdAt.getName().equals(origin)) {
        parts[i] = "NOW()";
      } else if (lastModifiedAt != null && lastModifiedAt.getName().equals(origin)) {
        parts[i] = "NOW()";
      } else {
        parts[i] = COLON + origin;
      }
    }
    return String.join(",", parts);
  }

  protected String getRelationExistCountingWhereClause(Class<? extends T> targetClass) {
    List<String> innerSelects =
        getFields(targetClass).stream()
            .filter(field -> field.isAnnotationPresent(JoinColumn.class))
            .map(
                field -> {
                  JoinColumn joinColumn = field.getAnnotation(JoinColumn.class);
                  String tblName = field.getType().getAnnotation(Table.class).name();
                  return String.format(
                      WHERE_CLAUSE_QUERY_INNER_SELECT_FORMAT,
                      tblName,
                      joinColumn.referencedColumnName(),
                      COLON + field.getName());
                })
            .collect(Collectors.toList());
    int count = innerSelects.size();
    return String.format(
        WHERE_CLAUSE_QUERY_FORMAT, String.join(SPACE + PLUS + SPACE, innerSelects), count);
  }
}
