spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      maximum-pool-size: 20
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
  jpa:
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
          time_zone: UTC
  data:
    jpa:
      repositories:
        # this is mandate as of initialization of JPA repositories
        # may live under the process EVEN AFTER the batch job is finished.
        # this is also can be a potential reason of spring batch not being exited
        # immediately after the job is done.
        bootstrap-mode: default