spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      maximum-pool-size: 20
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
logging:
  level:
    io.dsub: DEBUG
    org:
      reflections: ERROR
      springframework: ERROR
      hibernate: ERROR
    com.zaxxer.hikari: ERROR
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false