spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      maximum-pool-size: 20
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
  mvc:
    throw-exception-if-no-handler-found: true
  jpa:
    generate-ddl: true
logging:
  level:
    org:
      reflections: ERROR
      springframework: ERROR
      hibernate: ERROR
server:
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false