spring:
  main:
    web-application-type: NONE
    banner-mode: OFF
  datasource:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      maximum-pool-size: 20
  batch:
    initialize-schema: ALWAYS
    job:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20000
          time_zone: UTC
logging:
  level:
    io.dsub: DEBUG
    org:
      reflections: ERROR
      springframework: ERROR
      hibernate: ERROR
    com.zaxxer.hikari: ERROR