name: Publish to GitHub Packages
on:
  release:
    types: [created] # creating release from repo will auto trigger this action!
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Publish package
        run: gradle publish
        env:
          # token that has access to package-related actions
          PKG_TOKEN: ${{ secrets.PKG_TOKEN }}
          # github username
          USERNAME: ${{ secrets.USERNAME }}